### PR TITLE
unitaryCON landing page

### PR DESCRIPTION
**Pull request by WrathfulSpatula**
(I need to see the preview and iterate, before this is ready.)

### CODE REVIEW

**Comment by WrathfulSpatula** [comment]
This is ready for review, now!

**Comment by willzeng** [comment]
Thanks @WrathfulSpatula a few comments:
- We don't need to link to it on the homepage or in the nav as it is invite-only
- Can remove the unitaryCon header as the image is sufficient: 
image
- Let's make all the text after the first paragraph smaller font like on this page: https://unitary-fund-prel-git-unitaryconlandingpage-unitary-fund.vercel.app/ideas/
- Can we center the image and text like in a blog post? https://unitary-fund-prel-git-unitaryconlandingpage-unitary-fund.vercel.app/posts/2023_mitiq_nsf_pose

**Review by willzeng — CHANGES_REQUESTED** [review]
Changes in comment above

**Comment by WrathfulSpatula** [comment]
@willzeng It's easy to resize the image, if anyone has a strong opinion on it. I tried to implement your changes, but there some limitations, working within the app's framework.

**Review by willzeng — APPROVED** [review]
LGTM!

**Comment by nathanshammah** [comment]
@WrathfulSpatula, if I look at the latest deployment by the bot on the latest commit (["View deployment"](https://unitary-fund-prel-9emrpcxsh-unitary-fund.vercel.app/)) I cannot find the web page in the menu. Can we add it there?

**Comment by WrathfulSpatula** [comment]
@nathanshammah See the change requests from @willzeng, above: because the event is invitation-only, he asked me to take it out of the navbar. (It can be done either way, but reviewers need to reach a consensus on the requirement.)

**Comment by nathanshammah** [comment]
Gotcha!

**Pull request merged**
