### PR TITLE
Add an RSS feed for blog posts

### PR DESCRIPTION
**Pull request by cosenal**
At UnitaryCON, @1ucian0 reminded me of my past as a developer of an open-source rss reader, so I felt a moral obligation to add an RSS feed to the Unitary Fund blog.

Partially solves #49. Inspired by this one, we can create an easy follow-up PRs for other pages (e.g. grants.) 

Implemented following https://docs.astro.build/en/guides/rss/

**Tested** with [NetNewsWire](https://netnewswire.com/):
- run the app with `pnpm dev`
- add `localhost:3000` as a «New Feed» on NetNewsWire

Screenshot 2024-09-16 at 09 50 46

### CODE REVIEW

**Comment by nathanshammah** [comment]
@cosenal thanks for adding this. I wonder if we can address it also for grants (see #49), in the future. That said, how do you subscribe / find out if you are a visitor? There is an RSS icon showing in the browser? I cannot inspect the page, as tests, are failing, not sure why, see #547.

**Review by vprusso — APPROVED** [review]

**Review by nathanshammah — APPROVED** [review]
Thanks @cosenal! I missed the comment on the grant feed, +1 from me to open a new PR for that too. 

Regarding including the link: if we don't, I feel it would be very hidden. Not sure how RSS is used these days, but what about having a simple link under a text, in the main file, https://github.com/unitaryfund/unitary.fund/blob/blog-rss/src/pages/blog.mdx, 
of the kind of: 
"Stay up to date with new blog posts by joining the [UF Discord server], subscribing to our quarterly [newsletter] or subscribing to the [RSS feed]". In any case feel free to merge.

**Comment by cosenal** [comment]
@nathanshammah Thanks for the review! I merged it so we can also test it on the live website. I will create a followup PR with the text you suggested and an alternate feed for grants.

**Comment by cosenal** [comment]
Nice, @1ucian0! 
_RSS is not dead!_ ✊

**Comment by amirebrahimi** [comment]
Certainly not! I still use: https://ifttt.com/feed

**Pull request merged**
