### PR TITLE
Create 2024_Looking back at unitaryCON.md

### PR DESCRIPTION
**Pull request by KallieFerguson**

### CODE REVIEW

**Comment by nathanshammah** [comment]
@KallieFerguson thanks, reads great! 

I don't know why the continuous integration is failing, but my guess is due to the images, as this happened before. Unfortunately, it seems that the easiest way to include images at this time is not working. Can you please try to add the images using ["option 2" in the readme](https://github.com/unitaryfund/unitary.fund?tab=readme-ov-file#adding-images)? You'll need to upload the files and link them, all on this same branch.

**Comment by KallieFerguson** [comment]
Thanks, Nathan. It looks like I'm unable to do option 2 either because I get this error trying to upload "Uploads are disabled.
File uploads require push access to this repository."

**Comment by nathanshammah** [comment]
@KallieFerguson if you go to https://github.com/KallieFerguson/unitary.fund/tree/patch-9, you are able to select "Add file", right?

You then need to also modify the file with the embedded image, `alt text`.

**Review by nathanshammah — APPROVED** [review]
Thanks, looks great @KallieFerguson!

**Pull request merged**
