### PR TITLE
Updating bibliography page

### LINKED ISSUE #360: Add new publication to research page
https://arxiv.org/abs/2306.15863

### PR DESCRIPTION
**Pull request by vprusso**
Closes #360, #343 

@nathanshammah

### CODE REVIEW

**Comment by vprusso** [comment]
Added in cb3f81c @nathanshammah

**Review by nathanshammah — CHANGES_REQUESTED** [review]
- @vprusso thanks. There are still some small can you please unify the formatting of citations? E.g., `Phys. Rev. A **87**, 39 (2022) [2022.4385]`, not with "pages" spelled out etc.
- Add to Mitiq paper: "Quantum 6, 774 (2022)."
- Make sure after titles there is a comma
- Can you also please check other papers in the page for consistency?

**Comment by vprusso** [comment]
Thanks for the comment, @nathanshammah 

Addressed in 501ede2

**Review by nathanshammah — APPROVED** [review]
Thanks @vprusso!

**Pull request merged**
