### PR TITLE
Create 2023_Piccolo.jl.md

### PR DESCRIPTION
**Pull request by KallieFerguson**
Q4 2023 new grant announcement

### CODE REVIEW

**Comment by KallieFerguson** [comment]
@nathanshammah I think somehow this failed to be under grant too for some reason, but I don't see where I can edit it.

**Comment by KallieFerguson** [comment]
Ok I see what happened, I copied and pasted the format for the header and then went an extra backspace, which got rid of the grant. I can watch this in the future, but if there is a way for me to edit that mistake now, please let me know!

**Comment by nathanshammah** [comment]
@KallieFerguson I took care of it now.. For the future: 
 From web:
`Files changed> ...> Edit file>` Rename the file on the top with the added nested structure (appending 'grant/' just before `content/`). Snapshots below. 


**Screenshot 1**
gh-file-name


**Screenshot 2**
gh-file-name-2

**Comment by KallieFerguson** [comment]
Thanks! It looks like I don't have permissions to edit after I submit it, it's all greyed out and won't allow me to check it, so I'll need to just keep an eye on that. Thanks for merging!

**Pull request merged**
