### PR TITLE
Create 2024_teaching_learning_in_high_schools.md

### PR DESCRIPTION
**Pull request by kaitlinmgili**
Blog post about my Iteration One project, funded by UnitaryFund!

### CODE REVIEW

**Comment by cosenal** [comment]
Hi @kaitlinmgili, thanks for writing this. Your file must be inside the https://github.com/unitaryfund/unitary.fund/tree/main/src/content/blog folder.

**Review by kaitlinmgili — COMMENTED** [review]
Placed inside of blog folder

**Review by kaitlinmgili — COMMENTED** [review]
Added inside of blog folder

**Comment by kaitlinmgili** [comment]
Not sure what could be the conflict now?

**Comment by cosenal** [comment]
> Not sure what could be the conflict now?

I suspect it's something about the image asset. Do you mind trying Option 2 from https://github.com/unitaryfund/unitary.fund?tab=readme-ov-file#adding-images? 🙏

**Comment by cosenal** [comment]
@natestemen @WrathfulSpatula I added you two as reviewers, because also champions of the project.

**Review by natestemen — APPROVED** [review]
Great write up Kaitlin! Really cool to read about your experience. I hope this inspires others to do similar.

If you can try Alessandro's suggestion for the image, I think this should be good to go (or at least debugging will be easier)!

**Comment by kaitlinmgili** [comment]
I have tried to do Option 2 for the image, but it's telling me that I don't have permission to upload an image. Perhaps this is something you could do on your end? Thanks! 

2024_high_schools

**Comment by cosenal** [comment]
@kaitlinmgili I uploaded the image for you, and added tags too. We still need to change the publication date, and then we can merge.

**Review by kaitlinmgili — COMMENTED** [review]
Updated the date

**Comment by natestemen** [comment]
@francespoblete tagging you since we may want to make a social post promoting Kaitlin's write up :)

**Pull request merged**
