### PR TITLE
Add Ali profile pic

### PR DESCRIPTION
**Pull request by nathanshammah**
Add Ali profile pic to his blog post about the 2023 Summer internship.

### CODE REVIEW

**Comment by nathanshammah** [comment]
@WrathfulSpatula any idea how we can make this look smaller?

**Comment by natestemen** [comment]
Looks like the suggestion is to use html with a `width` attribute: https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown
```html
<img src="drawing.jpg" alt="drawing" width="200"/>
```

**Comment by WrathfulSpatula** [comment]
Thank you, @natestemen. Yes, that sounds right.

**Comment by natestemen** [comment]
@WrathfulSpatula I cannot test the change locally to ensure it works as I do not know how to spin up the website locally (opened https://github.com/unitaryfund/unitary.fund/issues/358 to hopefully get this documented). Would you mind taking this?

**Pull request closed without merging**
